INSERT IGNORE INTO courses (title, slug, short_description, full_description, category_id, level, featured, status, sort_order) VALUES
('C Programming', 'c-programming', 'Build strong logic, core programming and problem solving skills from zero.', 'C Programming Mastery: Programming Basics, Control Flow, Arrays, Strings, Pointers, Dynamic Memory, Functions, Recursion, Structures, Macros, File Handling, Debugging and Mini Projects.', 1, 'Beginner', 1, 1, 1),
('C++ Programming', 'cpp-programming', 'Master C++ foundations: namespaces, OOP, memory management, STL and practical projects.', 'Includes namespaces, classes, inheritance, polymorphism, constructors, destructors, operator overloading, exceptions, templates, STL containers, and file handling.', 1, 'Intermediate', 1, 1, 2),
('Java Programming', 'java-programming', 'Learn Java fundamentals, OOP, exception handling, collections and file handling.', 'Covers data types, control flow, methods, constructors, inheritance, polymorphism, interfaces, packages, exception handling, and GUI basics.', 1, 'Beginner', 0, 1, 3),
('Python Programming', 'python-programming', 'Master Python foundations: data types, control flow, functions, collections, OOP and file handling.', 'Includes variables, loops, lists, dictionaries, strings, functions, modules, recursion, OOP, exception handling and file operations.', 1, 'Beginner', 1, 1, 4),
('Data Structures & Algorithms', 'data-structures', 'Comprehensive DSA covering arrays, linked lists, stacks, queues, trees, graphs and more.', 'Fundamentals, linked lists, stacks, queues, searching, sorting, trees (BST, AVL, B-tree), graphs (BFS, DFS, MST, shortest paths) and complexity analysis.', 6, 'Advanced', 0, 1, 5),
('Data Science', 'data-science', 'Master data analysis, visualization, ML and AI using Python and modern libraries.', 'Python, advanced Python, OOP, data analytics, databases (MySQL, MongoDB, SQLite, Firebase), server-side development, AI/ML, statistics, Power BI.', 3, 'Advanced', 1, 1, 6),
('Data Science Foundation', 'data-science-foundation', 'Start your journey into Data Science with programming, data handling and creative AI.', 'Programming & Logic, Python Basics, Problem Solving, Introduction to Data, Pandas, NumPy, Visualization, Basic Statistics, Mini Project, Creative AI Skills.', 3, 'Beginner', 0, 1, 7),
('MERN Full Stack', 'mern-full-stack', 'Learn MongoDB, Express, React and Node to build modern scalable web applications.', 'Web Foundation, Advanced JavaScript, React, Node.js, Express, MongoDB, REST APIs, Authentication, Full Stack Projects and Deployment.', 2, 'Intermediate', 1, 1, 8),
('Java Full Stack', 'java-full-stack', 'Complete Java backend and frontend development including Spring Boot and REST APIs.', 'Core Java, Advanced Java, JDBC, Servlets/JSP, Frontend (HTML/CSS/JS/React basics), Spring Boot, REST APIs, JPA/Hibernate, Authentication, Deployment.', 2, 'Advanced', 1, 1, 9),
('Mobile App Development', 'mobile-app', 'Build native Android, iOS and Web apps using Flutter, Dart and Firebase.', 'Flutter basics, Dart, widgets, navigation, forms, APIs, state management (Provider, Bloc, GetX), local storage (SQLite, Hive), Firebase auth, animations, deployment.', 4, 'Intermediate', 1, 1, 10),
('UI/UX Design', 'ui-ux', 'Master modern UI/UX using Figma, Canva, AI-powered workflows and design systems.', 'Canva, Figma, Adobe Photoshop, CorelDRAW, AI-Design Tools, Branding & Visual Identity, Documentation & Design Systems.', 5, 'Beginner', 0, 1, 11),
('Kids Programming', 'kids-programming', 'Programming for ages 7-16: logic building, Scratch, Python, web basics and AI awareness.', 'Computer Basics, Logic Building, Scratch, Games, Python Basics, Web Basics, AI Introduction, Creative Technology, Final Project.', 7, 'Beginner', 0, 1, 12);
